root: ./

structure:  
   summary: SUMMARY.md
    
redirects:  
   company/how-to-guides-for-staff/how-to-spend-company-money: /operations/finance/how-to-spend-company-money/README.md
   company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract: /operations/finance/spending-company-money/how-to-procure-a-vendor-contract.md
   company/how-to-guides-for-staff/how-to-spend-company-money/how-to-use-expensify: /operations/finance/staff-member-expenses/how-to-use-expensify.md
   company/how-to-guides-for-staff/how-to-spend-company-money/airfare-and-traveling: /operations/finance/staff-member-expenses/airfare-and-traveling.md
   company/how-to-guides-for-staff/how-to-spend-company-money/how-to-reimburse-the-company: /operations/finance/staff-member-expenses/how-to-reimburse-the-company.md
   company/how-to-guides-for-staff/how-to-spend-company-money/currency-exchange-table: /operations/finance/staff-member-expenses/currency-exchange-table.md
   company/how-to-guides-for-staff/how-to-purchase/how-to-arrange-a-bounty-program: /operations/finance/staff-member-expenses/how-to-arrange-a-bounty-program.md
   company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid: /operations/finance/staff-member-expenses/how-to-get-paid.md
   company/how-to-guides-for-staff/how-to-purchase/request-a-divvy-virtual-credit-card: /operations/finance/spending-company-money/procurement/request-a-divvy-virtual-credit-card.md
   company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/README: /operations/finance/spending-company-money/procurement/how-to-on-board-as-a-vendor/README.md
   company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-invoice-mattermost: /operations/finance/spending-company-money/procurement/how-to-invoice-mattermost.md
   company/how-to-guides-for-staff/how-to-purchase: /operations/finance/how-to-spend-company-money/README.md
   company/about-mattermost/mindset#likes-and-wishes: /company/about-mattermost/mindsets.md#likes-and-wishes.md
   contributors/onboarding/staff-on-boarding-guide#leadership-principles: /company/about-mattermost.md#leadership-principles.md
   contributors/onboarding/staff-on-boarding-guide: /operations/workplace/people/working-at-mattermost/onboarding/staff-onboarding-guide/README.md
   contributors/mattercon: /contributors/join-us/recruiting.md#working-and-meeting-across-the-globe.md
